---

- name: "Run test » {{ test_to_run }}"
  command: "python3 -m unittest -vv {{ test_to_run }}"
  args:
    chdir: /opt/osbuild
  register: osbuild_test_run
  async: 1200
  poll: 0

- name: "Waiting for test to finish » {{ test_to_run  }}"
  async_status:
    jid: "{{ osbuild_test_run.ansible_job_id }}"
  register: job_result
  until: job_result is finished
  retries: 40
  delay: 30

- name: Set a fact if the test failed
  set_fact:
    all_tests_passed: no
  when:
    - job_result is failure
